### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by fzhbioinfo** [VCCRI/Spliceogen#1]
Hi. I got the following error. What could be the cause? 

$ sh RUN.sh -input toy/toy.vcf -gtf toy/toy.gtf -fasta toy/toy.fa
Input file: toy.vcf
Retrieving strand info...
Retrieving flanking FASTA sequence...
Scanning for motifs...
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: seqScan has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
No input for MaxEntScan
No input for GeneSplicer
No MaxEntScan/GeneSplicer/ESRseq scores to process

$ javac -version
javac 1.8.0_192

$ java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (Zulu 8.33.0.1-linux64) (build 1.8.0_192-b01)
OpenJDK 64-Bit Server VM (Zulu 8.33.0.1-linux64) (build 25.192-b01, mixed mode)

**Comment by smonger** [comment]
I suspect recompiling with your java version will resolve this. If so, I'll include this by default, in case others have the same issue.

Can you try again after running:
>javac bin/seqScan.java
>javac bin/mergeOutput.java
>javac bin/processScoresMES.java

Thanks,
Steve

**Comment by fzhbioinfo** [comment]
Thanks for your reply ! I'm running :
javac bin/seqScan.java
javac bin/mergeOutput.java
javac bin/processScoresMES.java
, it's fine. I run `sh RUN.sh -input toy/toy.vcf -gtf toy/toy.gtf -fasta toy/toy.fa` again, and it's worked!
I'm not sure what happened.
Another question:
It seems that I can only run the 'RUN.sh' in 'Spliceogen/' directory. I want to run it in other directory. What should I do?

**Comment by smonger** [comment]
Great, thanks. Unfortunately for now, it's a requirement to run it from this directory. This is due to MaxEntScan, with its usage of relative file paths for splicemodels etc. I'll fix this for the next update.

**Comment by fzhbioinfo** [comment]
You could add 'use FindBin qw($Bin)' into score5.pl and score3.pl. Then modify 'my %me2x5 = &makescorematrix("$Bin/me2x5")' and 'my %seq = &makesequencematrix("$Bin/splicemodels/splice5sequences")' in score5.pl. And modify 'my $dir = "$Bin/splicemodels/" ' in score3.pl.  And then you could run MaxEntScan in other directory. Hope this helps!

**Comment by smonger** [comment]
That looks like it will do the trick. Thanks very much!
